### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by lukeeey** [StatesOfJersey/bustracker#1]
I know that i can request the bus locations from [`https://sojbuslivetimespublic.azurewebsites.net/api/Values/GetMin`](#), but how does that data get there in the first place? Is there some system in place on the bus that transmits the location back to somewhere which then publishes it to azure? or something else?

I was also wondering this with the live carpark spaces data at [`https://sojpublicdata.blob.core.windows.net/sojpublicdata/carpark-data.json`](#) if you have any information about that.

**Comment by marcusferbrache** [comment]
Hi Luke. There's more information available about the system at:

- https://www.gov.je/Government/PublicSectorReform/eGovernment/Projects/Pages/TrackMyBus.aspx
- https://blog.gov.je/2016/02/01/track-my-bus/

I don't think we've published anything about how the car park space system works. Basically, 'loop counter' sensors at the barriers and points of exit in the multi-storey car parks are connected to a PC at Sand Street, and that PC calculates the number of spaces and pushes the data to Azure.

**Comment by lukeeey** [comment]
Thanks for the info
